### PR TITLE
Add libfmt-9 compatibility

### PR DESCRIPTION
**Pull request by repojohnray**

### CODE REVIEW

**Comment by alandefreitas** [comment]
How does an unused formatter help the application?

**Comment by repojohnray** [comment]
This is required for libfmt-9, for instance: https://github.com/gentoo/gentoo/blob/master/net-wireless/gnuradio/files/gnuradio-3.10.3.0-fix-fmt-v9.patch

**Comment by alandefreitas** [comment]
Yes. I know fmt needs a formatter _if you want to format custom types_. But this application doesn't format these types into format strings. What changed?

**Comment by repojohnray** [comment]
This is a quick fix for compiling with libfmt-9. A better solution could exist.

**Pull request merged**
