### PR TITLE
download and build boost if necessary

### PR DESCRIPTION
**Pull request by threaderic**
hello Alan!
Thanks for this useful app.

As I used your program, I met two minors issues solved by this pull request:
- update CmakeLists.txt:
if Boost library not found or Version < 1.78.0
fetch and install Version 1.81.0
- fix minor bug to avoid printing help arguments twice

### CODE REVIEW

**Comment by alandefreitas** [comment]
Thanks. To be honest, 1.78.0 is just the version I had at the time. If you want you can even test it to see how low this can go.

In your `set(BOOST_INCLUDE_LIBRARIES filesystem system program_options)`, I believe we need to list the libraries we use, such as process and asio to let the Boost script figure out the dependencies.

**Comment by alandefreitas** [comment]
Is it good to go?

**Comment by threaderic** [comment]
I tested it on Linux and it works well.

**Comment by alandefreitas** [comment]
Okie dokie!

Thanks!

**Pull request merged**
